### PR TITLE
Update Travis

### PR DESCRIPTION
**Pull request by replaid**
Fix a broken Travis build, and add Ruby 2.2.

### CODE REVIEW

**Comment by timcraft** [comment]
@replaid Thanks! 2.2 definitely needs adding, but might as well wait a bit longer and add 2.3 and 2.4 together. I think it's time to drop 1.9, current version is stable enough that anyone still on 1.9 can stay pinned to that. Can you change this to removing 1.9 and adding 2.2-2.4, and then I can merge that as soon as travis is happy with it (not sure if 2.4 is on travis yet?).

**Comment by replaid** [comment]
Travis doesn't have anything higher than 2.2 according to the docs I found. Will get to this next week.

**Comment by replaid** [comment]
@timcraft This is ready to go. Kept the `gem install bundler` to support `jruby-head` (and perhaps just generally keep Travis out of flaky territory).

**Comment by timcraft** [comment]
@replaid Merged, thanks! 👍

**Pull request merged**
